Style/Documentation:
  Enabled: false

Style/ClassVars:
 Enabled: false

Metrics/ClassLength:
  Max: 270

Metrics/AbcSize:
  Exclude:
    - 'classes/main.rb'

Metrics/MethodLength:
  Max: 70

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10
